### ISSUE TITLE
🗪 Chat - 🚧 Basic User Metrics

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/engagement#190]
How can a bot display a raw count of basic metrics.

One of the bots currently deployed should have some of this capability.

**Todo**
- [ ] Figure out which bot has basic metrics
- [ ] create new basic metrics channel
- [ ] create new metrics role (server wide)
- [ ] give some people the metrics role
- [ ] don't forget to include this change in the Sept Chat Guild 

@SirAh0 
@0xAngle 
@zubepaul
