### ISSUE TITLE
Discord 5 

### ISSUE THREAD

**Issue by okoba** [smartcontractresearchforum/engagement#197]
### Discord 5 Internal Mini-grant
**Tasks**
- [x] Write Discord 5 with links
- [x] Announce on Discord research channel
- [x] Link to Socials Board

**Billing**
Billed at 30 DAI

 "Discord 5" Opportunity: 
Want to have a deep conversation while earning Source Cred?
Then join any of these discussions:
1. In this paper, The authors attempt to fill a significant gap in the literature by completing a systematization of governance properties for evaluating blockchain protocols. To Join this deep conversation, click the link: (https://www.smartcontractresearch.org/t/research-summary-sok-blockchain-governance/1768) 
2. In this work, we present a privacy-preserving and decentralized solution to this problem by using cryptographic tools like commitments, zero-knowledge proofs (ZKs) and secure multiparty computation (MPC), To join this deep discussion, click the link :https://www.smartcontractresearch.org/t/research-summary-privacy-preserving-decentralized-netting/1782/8
[](url)
3. REDSHIFT has garnered considerable interest, as this scheme does not require a trusted setup, nor does it rely on novel mathematical properties, to learn more about the problems REDSHIFT solves and engage with the summary, click the link below: (https://www.smartcontractresearch.org/t/research-summary-redshift-transparent-snarks-from-list-polynominal-commitment-iops/344/11)
4.  In this paper, the researchers propose a platform-independent mechanism to recover high-level DeFi semantics and detect price manipulation attacks using patterns expressed in the recovered DeFi semantics, join this deep conversation by the link: (https://www.[smartcontractresearch.org/t/research-summary-defirangers-detecting-price-manipulation-attacks-on-defi-applications/1657)
5. How are liquidation mechanisms structured in DeFi lending platforms and what effects do these structures have on borrowers, lenders, and liquidators? get a sublime response to this core question by clicking the link below: (https://www.smartcontractresearch.org/t/research-summary-an-empirical-study-of-defi-liquidations-incentives-risks-and-instabilities/1952)

**Comment by zubepaul** [comment]
@MichaelSCRF Discord 5 issue is now up

**Comment by MichaelSCRF** [comment]
@zubepaul, this Discord 5 is published and this issue is prepared to be closed.
