### ISSUE TITLE
🗪 [🚧] >Welcome #🏁start-here Branding

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/engagement#20]
### Related Tasks
SCRF Org Readme
https://github.com/smartcontractresearchforum/research_team/issues/248

Org ReadMe #115
https://github.com/smartcontractresearchforum/discovery/issues/115

### Launch Ready Task List

- [x] Schedule a meet with @SirAh0 to implement the change on test server
- [ ] Pick a launch window for this change to go live 
- [ ] Ensure your change is launch ready before the launch window
- [ ] After a month, schedule a follow up meeting with @SirAh0 to explain why this change was a success
- [ ] Document pipeline approval, if applicable @marvino3

### Benefits

- above the fold
- important SCRF links
- combine input from all verticals
- design pass
- brand alignment

The objective of the Start Here page is to provide new users an easy to navigate list of links throughout the SCRF landscape. Organizing content into brief and clearly marked sections will make digestion of content much easier. Currently, Chat is having channel creep and it can be overwhelming for new users to acclimate to the server. The Start Here channel is our captive audience moment to provide these users with a useful roadmap. This high level set of links should also be consistent across other properties such as the GitHub Org Readme for example. This effort will combine the settled upon copy with a design pass from Discovery. 

### Change Request

Update the content of the [>Welcome #🏁start-here](https://discord.com/channels/784234332617048065/962837574991376494) channel according to the [SCRF Google Docs File](https://docs.google.com/document/d/1i8kDcy4yCmJZX1Trm_agHmI495OUY9lzk_vFqYmYh5g/edit?usp=sharing)

**Implantation on test server**
https://discord.com/channels/935692452478718054/937767717375713320

### Tasks
- [x] transcribe test server start here to google doc, share with @marvino3 
- [x] update live server to match test server

### People

@marvino3 @vincenzospaghetti @zubepaul @SirAh0 @eleventh19

**Comment by SirAh0** [comment]
- [ ] @SirAh0 Add this ticket to the [PB](https://github.com/orgs/smartcontractresearchforum/projects/18/views/1)

**Comment by SirAh0** [comment]
- [ ] setup live server with @SirAh0 take

**Comment by SirAh0** [comment]
The objective of the Start Here page is to provide new users an easy to navigate list of links throughout the SCRF landscape. We should avoid having too much information here, or a lot of text so as to not overwhelm the user with information. Chat (Discord) can be intimidating to find information or understand where to go especially for users not familiar with Discord. The Start Here channel is our captive audience moment. This high level set of links should also be consistent across other properties such as the GitHub Org Readme for example. This effort will combine the settled upon copy with a design pass from Discovery.

**Comment by SirAh0** [comment]
@zubepaul

**Comment by SirAh0** [comment]
Meeting was held between Discovery Head and Engagement Head approval to use current state of the start here on test server for live.

Next launch window will include further refinements and design / branding pass.

**Comment by SirAh0** [comment]
live
