### ISSUE TITLE
Moderation Bounty

### ISSUE THREAD

**Issue by zubepaul** [smartcontractresearchforum/engagement#203]
### Description
This bounty covers tasks related to moderation at the contributor level. It requires membership in the moderation team to accomplish and claim.

### Tasks
- [x] Discord 5 for weeks starting 9/26/2022 and 10/3/2022

**Moderation cultivation for the following threads**
- [x] https://www.smartcontractresearch.org/t/research-summary-understanding-security-issues-in-the-nft-ecosystem/1350
- [x] https://www.smartcontractresearch.org/t/research-summary-design-and-implementation-of-blockchain-based-e-voting/1885
- [x] https://www.smartcontractresearch.org/t/discussion-post-a-stable-legal-framework-for-digital-uniqueness/561
- [ ] https://www.smartcontractresearch.org/t/research-summary-i-told-you-tomorrow-practical-time-locked-secrets-using-smart-contracts/953
- [x] Attend engagement vertical meeting 9/26/2022 and 1:1

### Billed for
- #197 
- #198 
- Remainder of this bounty is 300 DAI

**Comment by okoba** [comment]
Thread curation #197 

**Proposed Summary 
[]https://docs.google.com/document/d/1tzjb2gY1tmQVJ_olDcMuPNIe_RdyjGDScyj55jMi1eg/edit?usp=sharing
  
  ** Proposed Tag : DEFI , ethereum, manipulation,game theory, securitization

  ** Table of content.
   1. Summary post 
   2. Researchers proposal   
   3. random questions and author's response
   4. proposed solutions

 ** **Threads of interest** 
here's a list of discussions with relation to the post 
 1. []https://www.smartcontractresearch.org/t/research-summary-sok-decentralized-finance-defi/1055/6?u
 2. https://www.smartcontractresearch.org/t/research-summary-a-short-survey-on-business-models-of-decentralized-finance-defi-protocols/1947/6?u[]
 3. https://www.smartcontractresearch.org/t/research-summary-what-is-in-your-wallet-privacy-and-security-issues-in-web-3-0/1225/10?u[]

**Comment by okoba** [comment]
@zubepaul

**Comment by zubepaul** [comment]
@okoba What are the links to the table of contents?

**Comment by okoba** [comment]
1. Proposed document :[https://docs.google.com/document/d/1y4lj062WU0QPSokTGDL5PSBAoBxPSLl_oPAEg7Hjj40/edit?usp=sharing]

2.3. Threads of interest.
1.(https://www.smartcontractresearch.org/t/research-summary-defirangers-detecting-price-manipulation-attacks-on-defi-applications/1657/10?u
2. https://www.smartcontractresearch.org/t/research-summary-sok-decentralized-finance-defi/1055/2?u
3. https://www.smartcontractresearch.org/t/research-summary-sok-decentralized-finance-defi/1055/3?u
4. https://www.smartcontractresearch.org/t/research-summary-a-short-survey-on-business-models-of-decentralized-finance-defi-protocols/1947/4?u

3. proposed tags :  DEFI , Ethereum, manipulation,game theory, securitization

**Comment by okoba** [comment]
@zubepaul the table of content is apart of the doc i sent earlier

**Comment by okoba** [comment]
1. Proposed document; https://docs.google.com/document/d/1ql_GrVt9a-IcZMgCy5pcUykPOevVmpwFBFZms7ojfM0/edit?usp=sharing[]
2. Threads of interest .
1.https://www.smartcontractresearch.org/t/research-summary-understanding-security-issues-in-the-nft-ecosystem/1350/6?u[]
2.https://www.smartcontractresearch.org/t/research-summary-understanding-security-issues-in-the-nft-ecosystem/1350/13?u[]
3.https://www.smartcontractresearch.org/t/research-summary-understanding-security-issues-in-the-nft-ecosystem/1350/15?u[]
4.https://www.smartcontractresearch.org/t/research-summary-attacks-on-smart-contracts/1826/4?u[]
5.https://www.smartcontractresearch.org/t/research-summary-attacks-on-smart-contracts/1826/5?u[]

3. proposed tags :Defi, securityNFT

**Comment by okoba** [comment]
@zubepaul

**Comment by okoba** [comment]
Proposed doc .
[](https://docs.google.com/document/d/1xz2SBN57GzBCnNU7VrdGMGM-6_mmeXbcPm6XMHRuCuw/edit?usp=sharing


Threads of interest.
here's a list of top comments about the topic ;
1. https://www.smartcontractresearch.org/t/research-summary-design-and-implementation-of-blockchain-based-e-voting/1885/14[]
2. https://www.smartcontractresearch.org/t/research-summary-design-and-implementation-of-blockchain-based-e-voting/1885/20?u[]
3. https://www.smartcontractresearch.org/t/research-summary-design-and-implementation-of-blockchain-based-e-voting/1885/18?u[]

Proposed tags .
blockchain, e-voting, game theory

**Comment by okoba** [comment]
proposed doc ;
https://docs.google.com/document/d/13Ma_NmclRF9aO9-QQ87uze09VMr6EgMQX8EBO_h9RYc/edit?usp=sharing[]

 threads of interest .
1. https://www.smartcontractresearch.org/t/discussion-post-a-stable-legal-framework-for-digital-uniqueness/561/15?u[]
2. https://www.smartcontractresearch.org/t/discussion-post-a-stable-legal-framework-for-digital-uniqueness/561/13?u[]
3. https://www.smartcontractresearch.org/t/research-summary-a-decentralized-framework-for-patents-and-intellectual-property-as-nft-in-blockchain-networks/1724/4?u
4. https://www.smartcontractresearch.org/t/research-summary-nft-wash-trading-quantifying-suspicious-behaviour-in-nft-markets/1982/17?u

proposed tags .
non-fungible, data, discussion

**Comment by okoba** [comment]
proposed doc : https://docs.google.com/document/d/13tKLzNyTtlFuH3EZVHD71riZ0h6h9b1aCtxN3wH2Vuo/edit?usp=sharing[]

threads of interest.
1. https://www.smartcontractresearch.org/t/research-summary-post-quantum-security-of-the-bitcoin-backbone-and-quantum-multi-solution-bernoulli-search/263/5?u[]
2. https://www.smartcontractresearch.org/t/research-summary-post-quantum-security-of-the-bitcoin-backbone-and-quantum-multi-solution-bernoulli-search/263/6?u[]
3. https://www.smartcontractresearch.org/t/research-summary-attacks-on-smart-contracts/1826/4?u[]
4. https://www.smartcontractresearch.org/t/research-summary-attacks-on-smart-contracts/1826/8?u[]

proposed tags .
smart contract, security, game theory, computing

**Comment by okoba** [comment]
didn't anticipate that will drop the link

**Comment by zubepaul** [comment]
Tags updated on the forum.

**Comment by zubepaul** [comment]
Bounty will be considered completed and billable once all comments are on the forum.
