### ISSUE TITLE
SourceCred - October Agenda

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/engagement#211]
# Agenda

- Docs updated with new collapse format
- New Opt In location on Discord
- Review how to find previous guild notes and meets
- Ways to redistribute monthly unclaimed return cred

disbursement models @zubepaul 
- parameters of sourcecred
	- node / edge weights
- degredgation of score
- push rewards to active over inactive
- hybrid approach
	- recent activity v long
	- carve up the return pool
		- split for last month focus on a shorter time scale
		- recognize good new work
		- 
# Resources

🔗[Presentation Deck](https://docs.google.com/presentation/d/1rCU8KN4DmcVOwm8fRlFHuhq2ddpZVevM5M185BdPZ2U/edit?usp=sharing)

🔗 [September Agenda](https://github.com/smartcontractresearchforum/engagement/issues/185)

🔗 [Meet Recording](https://drive.google.com/file/d/1xr-B9xt5Zc7UafGBLWy9oe0AZo8cCMbY/view?usp=sharing)

# TODOs
- [x] Don't forget to record!
- [x] Update SCRF SCRED Doc.
- [x] Add recording link to above resource

**Comment by SirAh0** [comment]
how can we market this imitative
- target writers
- new opportunity to engage and get paid out for new content
- special run of offers to promote new content
- hello @smartcontractresearchforum/discovery

**Comment by Coinproz** [comment]
anti-plagiarism api for the sake of protecting the forum integrity

**Comment by Coinproz** [comment]
how to utilize past payouts and community compensation to encourage participation from industry writers that are being underpaid or exploited

**Comment by SirAh0** [comment]
how can we tell a user story who has risen up through the ranks

**Comment by Coinproz** [comment]
quantitative analysis in the form of sourcecred and qualitative analysis in the form of community feedback

**Comment by SirAh0** [comment]
matthew omeje
I started at 0. Think I'm at 1.4 now.
Harvesto also

@Coinproz 
also analyze how many 0 scores are in the population over time
0 score would represent people registering and not participating, so a lowering 0 score would be good, while an increase would be bad

**Comment by SirAh0** [comment]
@zubepaul 
year end sourcecred guild roll-up
all guild roll ups?

**Comment by Coinproz** [comment]
connect with michael and maria

**Comment by DecntrlzNP** [comment]
is there any way to recover the undelivered source cred due to, screenname change? I did not receive my contribution for last month but it was due to my smart @$$ changing it

**Comment by zubepaul** [comment]
@DePONotary Because unclaimed DAI goes into a return pool that gets distributed, there is not a way to recover prior DAI. If you make changes in the future like that, just fill out the form on Discord again and make a note of the change. I think that would solve that problem going forward.

**Comment by DePONotary** [comment]
> @DePONotary Because unclaimed DAI goes into a return pool that gets distributed, there is not a way to recover prior DAI. If you make changes in the future like that, just fill out the form on Discord again and make a note of the change. I think that would solve that problem going forward.  

Heard, and I think I have the form should be revise and have a place for notes just to also record the change.

**Comment by s-ben** [comment]
Very interesting [meeting](https://www.youtube.com/watch?v=VpY4PoXYMeY&t=2133s)!  A few reflections:

**On gaming:**

Glad to see this brought up. While SCRF is still "flying the party bus", this is the most important vulnerability IMO, especially if SCRF is looking to increase payouts. 

> anti-plagiarism api for the sake of protecting the forum integrity

Could see this being a problem, especially for academic content. @Coinproz also makes a good point about AI. In addition to automatic summaries, would also look out for Google Translate if SCRF starts accepting translations.

> if you try to game it, that’s the only way you lose” - @Coinproz 

This. While more sophisticated moderation involves due process, gradiated sanctions, etc., the most practical high-level aproach IMO from a game theoretic approach is to just trust people until they violate that trust. Then cut off anyone that clearly games. 

> So if people write poorly, or are bad at constructing argument, we’ll help you get better at that. We’ll help you get to our level, just as long as you demonstrate you’re not here just for the money. Even if here just for money, and acting in good faith and not breaking the rules then there’s nothing wrong. All these things create environment that is completely different than everything out there right now. Orgs within the space would want to foster

Was cool to see the program to help people level up their writing. Not something I've seen elsewhere. To make it sustainable, I do think you do need to make sure contributors are measurably improving and in dialogue/co-creation with the rest of the community (and ofc not gaming). But if you can achieve that, could create some very real accessibility at a scale many orgs aspire to but can't achieve in practice. 

**Instance tweaks**

@zubepaul, liking your ideas. While I like using all-time Cred for building long-term engagement, a short-term component would make the system more responsive and attractive to new contributors. This, combined with visibility/recognition elsewhere, is a powerful combination. 

You can create a separate instance for that, or configure the current instance to split rewards using different payout policies. For instance 50% all-time Cred, 50% last week. Which approach is best likely depends on a) how you display output data (e.g. do you want to display the all-time vs weekly payouts separately?), and b) admin overhead (i.e. is it easier to manage changes in one instance or two). 

**Marketing & recruiting**

@SirAh0, like the idea of promoting on social media. Would be down to RT from the sourcecred twitter and personal account. I'm hesitant to have opinions here, as it kinda depends on SCRF's goals around recruitment. Does SCRF want to cast a wide net, or be more targeted/selective?

@Coinproz I definitely think you could poach writers from CoinDesk, CoinTelegraph, etc. I used to be a freelance writer in the semiconductor industry, and can safely say it wouldn't be too hard to offer a better deal. The challenges I anticipate are:
- Explaining a very different model; less hard if the instance is functioning well and feedback is visualized, as then trust builds organically over time.
- Creating and articulating income guarantees. A common question when recruiting people from traditional systems is 'how much will I get for X contribution on average'? To answer that you have to a) relatively stable configuration that allows for predictable Cred flows, and b) do work of translating that to payout estimates (which means stability in payout mechanisms). The story will also be stronger if payouts are expected to extend into the future. But yeah, if you can make strong guarantees that quality content will accrue real "royalties" according to actual value delivered, and one can create a "portfolio" over time, that should be very compelling. 

**Data analysis**

@SirAh0 I think data analysis informs pretty much all of these questions. There is a good amount of existing data analysis code out there I can point you to if you have specific tasks. Data analysis generally is probably the highest leverage thing to work on IMO.

**Comment by SirAh0** [comment]
Thank you everyone for the feedback, I will try and summarize in todays meeting and continue the conversation.

**Comment by SirAh0** [comment]
> @SirAh0 I think data analysis informs pretty much all of these questions. There is a good amount of existing data analysis code out there I can point you to if you have specific tasks. Data analysis generally is probably the highest leverage thing to work on IMO.

That would be awesome!

**Comment by Coinproz** [comment]
Now might be a great time to stop paying people who sign up and don't participate if the goal is to encourage participation; in that paying people just to show up encourages people NOT to participate by giving them a reward in effect working against the goal.

**Comment by Coinproz** [comment]
how to leverage guild report and turn narrative around sourcecred experiment into research grants
