### ISSUE TITLE
Yesh and Paul's Calls

### ISSUE THREAD

**Issue by Yesh-2691** [smartcontractresearchforum/engagement#233]
Calls between Yesh and Paul are tracked here. Will be moved to an appropriate repo when it exists.

**Comment by Yesh-2691** [comment]
### Aug 19, 2022

- Where does the initial document from? Is it from the Content team ? - What is this? an Issue on Github.
- Does one document contain multiple Posts associated with it?
- Solution: Automation of Steps 1&2.
- Paul : From Engagement pipeline not connect with content pipeline. 
    - Whenever an issue is added to the ‘Under review’ list of the Moderation/engagement board and a moderator is assigned, 
        - Create a new row in excel (GTM tracking) with the following items, - make this redundant.
            - Github ticket link.
            - Moderator (assignee on GH).
            - Link to google doc (research summary for example) from the attached document.
                - Content side - This google doc might not exist. 
                - Researchers way of doing it : 
                    - Word doc to direct mark down on the Forum. 
                    - Draft TBC confirmed by Engagement team. 
                - Issue to directly be created on the Content Repo but visualised in the GTM board project pipeline project view. 
            - GTM strategy : Where should it live? 
                - Paul: On Github with few checklists. But could be public. 
                - Yesh: Google Doc to be linked on the 
            - New GTM doc is created automatically from a template and update the issue with the link.
            - Q : What the strategies to ensure this summary/research paper reaches wider in the community. 
                - Solution: Have a CRM with keywords showing interests and mail the summary and a link (to the forum) to those who are matching with keywords of this summary.
                - Does SCRF know the paper author(s)
			
                - This would help in 2 things, 
                    - ONE, We are connecting not so active researchers/industry/enthusiasts with things that are interesting to them. On repetition, it would encourage the external researcher to come to Forum. 
                    - TWO, Give a wider audience to the author of the paper. - Plays right into the mission of the SCRF of connecting different communities together. On repetition, this would encourage researchers and posters to put more content on the forum. 
                    - With both ONE and TWO, it ties back to SCRF and increased engagement. Maintaining a CRM would allow repetition and give 
- Why is the GTM doc not contain the GTM questions? This would allow internal SCRF researcher to just have all the information on one doc instead of 2 - reduces overhead. Some examples did not have this.
    - Paul agrees. 
- Why are questions on GTM strategy doc not asked. 
- Moderation doc : 
    * Cultivating a culture of peer review - Is this communicated thoroughly. 
Next time: 
- What is discord 5?
- Where is the final GTM process, where does it exist? Is it the GTM doc?
- Moderation doc : 
    * Cultivating a culture of peer review - Is this communicated thoroughly.

**Comment by Yesh-2691** [comment]
# 03 Nov, 2022

- Bring engagement projects on to the experimental board and investigate some bountiable tasks. 
- Checkin with Paul next week.
- Moderation: 
   - Discussion summary posts: 15 or more comments , Discussion summary from the moderator from [this template](https://docs.google.com/document/d/1OBFHVezq8WBAIzx-cbq8tZdS-_W5UKPv5wf2QnTSKk0/edit#heading=h.ue87ujlt2heb)
   - Check-in with... from [moderation process](https://forms.gle/DXAKKzvJYCjQ6ck38) and [this](https://docs.google.com/document/d/1BVBCGKxGptq87mBQswhGEL5C1cwGTdWTW6CzfvVOPZc/edit#heading=h.ktkatgp3ruyg)

**Comment by Yesh-2691** [comment]
#Next Time

- [x] Onboarding bounty template https://github.com/smartcontractresearchforum/engagement/issues/66 here . Is this final?
- [x] Need to clean up the issue boards. Suggest a 'On Hold' list on the view to make it clear. 

#Potential Bounties

- [x] smartcontractresearchforum/engagement#72 
- [x] smartcontractresearchforum/engagement#64 

To go on the Bounty board
- [x] smartcontractresearchforum/bounties#50 and some of the bounties you have on the eng repo. Moved
- [ ] smartcontractresearchforum/bounties#51 - How to implement Discourse test level here?.Moved
- [ ] smartcontractresearchforum/engagement#217 
- [x] smartcontractresearchforum/bounties#52 - Moved
- [x] smartcontractresearchforum/engagement#140 connects to epics well. Can use to give out some bounties.

GTM Process update: 

- An engagement strategy instead of GTM Process. 
- Bounty to Core or Contributors.

**Comment by Yesh-2691** [comment]
### 18 Nov 2022

- [x] New bounty board and changes made. 
- [ ] Create new bounties based on #140 
- [ ] Connecting Discourse trust levels to Bounty.

**Comment by Yesh-2691** [comment]
### 08 Dec 2022

- [ ] Last updated push on the GTM board to the assignee. The 'Bathroom' analogy by Paul. 
- [ ] There would a moderator on the GTM board. 
- [ ] Paul to make the bounties and update on the board. 
- [ ] Budget based bounty prioritizations from first week of Jan.
- [ ] Communication to the team on the bounty? thorugh [SCRF messaging board](https://github.com/orgs/smartcontractresearchforum/projects/18/views/1). 
- [ ] Bounty card to directly invoice after finishing the bounty. 
- [ ] External facing document and Internal facing bounty document in the messaging board.
