### ISSUE TITLE
[Yesh's personal] Engagement projects audit

### ISSUE THREAD

**Issue by Yesh-2691** [smartcontractresearchforum/engagement#234]
#Next Time

- [ ] Onboarding bounty template https://github.com/smartcontractresearchforum/engagement/issues/66 here . Is this final?
- [ ] Need to clean up the issue boards. Suggest a 'On Hold' list on the view to make it clear. 

#Potential Bounties

- [x] smartcontractresearchforum/engagement#72 
- [ ] smartcontractresearchforum/engagement#64 
- [ ] smartcontractresearchforum/bounties#52 
- [ ] smartcontractresearchforum/engagement#140 connects to epics well. Can use to give out some bounties.
- [x] smartcontractresearchforum/bounties#50 and some of the bounties you have on the eng repo.
