### ISSUE TITLE
🗪 Chat - Audit for Stale Channels

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/engagement#52]
### Reason for Change
There are currently a lot of channels that are not being used at all or very little. 

### Tasks
- [ ] Create a list of channels that have little to no activity
- [ ] Present this list in the next Discord Guild Meeting
- [ ] decide if they should be moved to the chopping block in the next Discord Guild Meeting
