### ISSUE TITLE
🗪 - Change Request

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/engagement#9]
### Tasks
- [ ] Schedule a meet with @SirAh0 to implement the change on test server
- [ ] Pick a launch window for this change to go live 
- [ ] Ensure your change is launch ready before the launch window
- [ ] After a month, schedule a follow up meeting with @SirAh0 to explain why this change was a success

### Benefits

it's going to be great, trust me.

### Change Request

turn it 25 degrees to the left.
