### ISSUE TITLE
Epic: Onboarding Process

### ISSUE THREAD

**Issue by zubepaul** [smartcontractresearchforum/engagement#94]
### Description
The current onboarding process is being re-evaluated and edited. 

**Steps**
- [x] Create an overall project plan
- [x] Create 1 month, 3 month, and 6 month project plans
- [ ] Create a maintenance schedule

**Resources**
- [SCRF Onboarding Epic Project Plan](https://docs.google.com/document/d/165eKYmPWhxD5gBJCBuzALimvzoNbBYSzV9HoabmnCPQ/edit#)
- smartcontractresearchforum/engagement#95 
- smartcontractresearchforum/engagement#96 
- smartcontractresearchforum/engagement#97
